title: <p align="center"> Braden Murray </p>

logo: "bmurr_pic.jpeg?raw=true" # your photo (or logo) here

description:
  <p align="center">
  <a href="B.Murray.Resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/brady-murray-703bab274">LinkedIn</a> |
  # <a href="https://github.com/bra-murray">GitHub</a>
  </p>

  
Data Analyst with two years of industry experience and a Master's in Data Analytics and Business Intelligence. Former Professional ice Hockey Player.
  <br><br>
  </p>
theme: jekyll-theme-minimal
# google_analytics: UA-145578661-1 # Google Analytics tracking ID
