title: <p align="center"> Braden Murray </p>
logo: "bmurr_pic.jpeg?raw=true" # your photo (or logo) here
description:
  <p align="center">
  <a href="B.Murray.Resume.pdf>Resume</a> |
  <a href="https://www.linkedin.com/in/brady-murray-703bab274"">LinkedIn</a> |
  <a href="https://github.com/ba-murray">GitHub</a>
  </p>
  
  <p Data Analyst with two years of experience. 
  </p>
  <p MSc in Data Analytics/ Business Intelligence.
  </p>
  <p Former Professional Hockey Player.
  </p>
theme: jekyll-theme-minimal
#google_analytics: UA-000000-0 # your Google Analytics tracking ID here
